import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import './globals.css'
import { db } from './modules/db'
import NewAccountCreator from './components/NewAccountCreator'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const accounts = await db.account.findMany({
    select: { id: true, name: true},
    orderBy: {name: 'asc'}
  })


  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen`}>
        <div className=' flex flex-col ps-4 gap-4
         bg-slate-800 text-slate-100 w-[240px]'>
          {accounts.map(account => (
            <Link key={account.id} href={`/accounts/${account.id}`}>
              {account.name}
            </Link>
          ))}
          <NewAccountCreator/>
        </div>
        <div className='flex-1'>{children}</div>
        
      </body>
    </html>
  )
}
